spring:
  profiles:
    group:
      local: "local, datasource, security, kakao"
      dev: "dev, datasource, security, kakao"
      prod: "prod, datasource, security, kakao"

logging:
  level:
    academy.zigee: debug
    org.springframework: debug